### ISSUE TITLE
Export to CSV ... better error message.

### ISSUE THREAD

**Issue by alexbenfica** [bkper/bkper-issues#43]
Does not specify what browser must be used.
It is Chrome, of course... but a more explicit message would be interesting.
I'm not sure if Bkper can change this, but here it is.

https://www.dropbox.com/s/g38d1e4tryi2u5p/Captura%20de%20tela%202015-11-29%2010.44.05.png?dl=0

**Comment by Jacobvdb** [comment]
Hi Alex, 

This is due to changes in the HTMLservice of Google Apps Script, you can read the information here http://googleappsdeveloper.blogspot.com.br/2015/10/google-apps-script-update-to-htmlservice.html

We have changed the sandboxmode so it should be working now. 
Let us know if the issue continues for you.
