### ISSUE TITLE
Rename groups

### ISSUE THREAD

**Issue by celsoreeks** [bkper/bkper-issues#53]
Being able to rename a group would be amazing (apparently, the only workaround for now is to remove the group and create a new one with the desired new name, which is quite counter intuitive).

**Comment by maelcaldas** [comment]
Hi Celso,

Thanks for the suggestion.

That makes sense. We will add to our backlog and keep you posted of the
progress here.

Thanks,
Mael


On Feb 14, 2018 18:23, "celsoreeks" <notifications@github.com> wrote:

Being able to rename a group would be amazing (apparently, the only
workaround for now is to remove the group and create a new one with the
desired new name, which is quite counter intuitive).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bkper/bkper-issues/issues/53>, or mute the thread

**Comment by celsoreeks** [comment]
Sweet!  Thanks for the feedback   :-)
